backend:
  name: github
  repo: cookiewolf/bi4c8d
  branch: main
publish_mode: editorial_workflow
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - name: "main-text" # Used in routes, e.g., /admin/collections/blog
    label: "Main text" # Used in the UI
    folder: "content/main-text" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Section", name: "section", widget: "select", options: ["section-one", "section-two", "section-three", "section-six", "section-nine", "section-eleven"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    identifier_field: "forwarded-from"
    fields:
      - { label: "Section", name: "section", widget: "select", options: ["section-one", "section-seven", "section-eleven"] }
      - { label: "Date & time", name: "datetime", widget: "datetime" }
      - { label: "Forwarded from", name: "forwarded-from", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "View count", name: "view-count", widget: "number" }
      - { label: "Avatar icon", name: "avatar-src", widget: "image" }

  - name: "message"
    label: "Message"
    folder: "content/message"
    create: true
    fields:
      - { label: "Section", name: "section", widget: "select", options: ["section-ten", "section-eleven"] }
      - { label: "Message Title", name: "title", widget: "string", hint: "Not displayed - for id in CMS" }
      - { label: "Side", name: "side", widget: "select", options: ["left", "right"] }
      - { label: "Date & time", name: "datetime", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "image"
    label: "Image"
    folder: "content/image"
    create: true
    identifier_field: alt
    fields:
      - { label: "Section", name: "section", widget: "select", options: ["section-two", "section-four"] }
      - { label: "Image", name: "source", widget: "image" }
      - { label: "Alt Description", name: "alt", widget: "string" }
      - { label: "Display position", name: "display-position", widget: "number" }

  - name: "graph"
    label: "Graph"
    folder: "content/graph"
    create: true
    fields:
      - { label: "Graph Title", name: "title", widget: "string" }
      - { label: "Dataset 1 Label", name: "label1", widget: "string", required: false }
      - { label: "Dataset 2 Label", name: "label2", widget: "string", required: false }
      - { label: "Dataset 3 Label", name: "label3", widget: "string", required: false }
      - { label: "Dataset 4 Label", name: "label4", widget: "string", required: false }
      - { label: "Dataset 5 Label", name: "label5", widget: "string", required: false }
      - { label: "Dataset 6 Label", name: "label6", widget: "string", required: false }
      - { label: "Dataset 7 Label", name: "label7", widget: "string", required: false }
      - label: "Datapoint"
        name: datapoints
        widget: list
        fields:
          - { label: "Date", name: "date", widget: "datetime", date_format: "DD MMM YYYY", time_format: false }
          - label: Data
            name: data
            widget: object
            fields:
              - { label: "Count1", name: "count1", widget: "number", required: false }
              - { label: "Tooltip1", name: "tooltip1", widget: "string", required: false }
              - { label: "Count2", name: "count2", widget: "number", required: false }
              - { label: "Tooltip2", name: "tooltip2", widget: "string", required: false }
              - { label: "Count3", name: "count3", widget: "number", required: false }
              - { label: "Tooltip3", name: "tooltip3", widget: "string", required: false }
              - { label: "Count4", name: "count4", widget: "number", required: false }
              - { label: "Tooltip4", name: "tooltip4", widget: "string", required: false }
              - { label: "Count5", name: "count5", widget: "number", required: false }
              - { label: "Tooltip5", name: "tooltip5", widget: "string", required: false }
              - { label: "Count6", name: "count6", widget: "number", required: false }
              - { label: "Tooltip6", name: "tooltip6", widget: "string", required: false }
              - { label: "Count7", name: "count7", widget: "number", required: false }
              - { label: "Tooltip7", name: "tooltip7", widget: "string", required: false }

  - name: "ticker"
    label: "Ticker"
    folder: "content/ticker"
    create: true
    identifier_field: label
    fields:
      - { label: "Label", name: "label", widget: "string" }
      - { label: "Total", name: "total", widget: "number" }
