backend:
  name: github
  repo: cookiewolf/bi4c8d
  branch: main
publish_mode: editorial_workflow
media_folder: public/images/uploads
public_folder: /images/uploads
collections:
  - name: "main-text" # Used in routes, e.g., /admin/collections/blog
    label: "Main text" # Used in the UI
    folder: "content/main-text" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {label: "Section", name: "section", widget: "select", options: ["section-one", "section-two"]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "message"
    label: "Message"
    folder: "content/message"
    create: true
    fields:
      - { label: "Date & time", name: "datetime", widget: "datetime" }
      - {label: "Section", name: "section", widget: "select", options: ["section-one", "section-two"]}
      - { label: "Forwarded by", name: "title", widget: "string", required: false }
      - {label: "Body", name: "body", widget: "markdown"}
      - { label: "View count", name: "view-count", widget: "number", required: false }
      - { label: "Avatar icon", name: "avatar", widget: "image" }
